name: CD
# build happens when docs changes merge to master
# test on docs-migration branch, need to update to master later
on:
  push:
    branches:
      - docs-migration

jobs:
  update-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "."
      - name: Commit documentation changes to gh-pages
        run: |
          git clone https://github.com/jina-ai/docs.git --branch gh-pages --single-branch gh-pages
          cp -r _build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "dev-bot@jina.ai"
          git config --local user.name "Jina Dev Bot"
          git add .
          git commit -m "update documentation due to ${{github.event_name}} on ${{github.repository}}" -a || true
      - name: Push changes to gh-pages
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.JINA_DEV_BOT }}
          force: true
