name: incremental-linkcheck

on:
  pull_request

jobs:
  sphinx-incremental-linkcheck:
    name: incremental-linkcheck
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout to docs repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pgip install -U jina
          pip install -r requirements.txt
      - name: Perform linkcheck
        shell: bash -l {0}
        run: |
          make linkcheck