name: CD
# build happens when docs changes merge to master/jina docstring get updated
on:
  push:
    branches:
      - fix-docs-backup

jobs:
  releaseJob:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout to Jina core
        uses: actions/checkout@v2
        with:
          repository: jina-ai/jina
          token: ${{ secrets.JINA_DEV_BOT }}
      - name: Install released Jina version
        run: |
          pip install .  --no-cache-dir
          JINA_VERSION=$(sed -n '/^__version__/p' ./jina/__init__.py | cut -d \' -f2)-master
          echo "JINA_VERSION=${JINA_VERSION}" >> $GITHUB_ENV
      - name: Checkout to docs repo
        uses: actions/checkout@v2
      - name: Build docs
        run: |
          echo -e "${{env.JINA_VERSION}}" >> versions
          cat versions
